### ISSUE TITLE
java.lang.Exception: Stack trace

### ISSUE THREAD

**Issue by fab-io** [iExecBlockchainComputing/public-pool-scripts#41]
My worker seems to be stuck, and prints this exception

```
[19/Dec/2018:08:49:00 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
08:49:08.563 [ThreadAlive] INFO  c.i.w.workerpool.WorkerPoolService - GetContributionModel [workOrderId:0xccb4c799749cf8b5a1cce4b3e813d335e55ea93d, transactionStatus:SUCCESS] 
==> about to get workOrderStatus
==> workOrderIsRevealing: false
[19/Dec/2018:08:49:11 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Ping = 807 ms
[19/Dec/2018:08:49:12 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Alive period from server = 60
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at xtremweb.common.WorkInterface.setRevealing(WorkInterface.java:2233)
	at xtremweb.worker.ThreadAlive.synchronize(ThreadAlive.java:477)
	at xtremweb.worker.ThreadAlive.run(ThreadAlive.java:136)
```

**Comment by fab-io** [comment]
now after some connection refused, it also log some more errors

```
08:57:52.097 [ThreadAlive] INFO  c.i.w.workerpool.WorkerPoolService - GetContributionModel [workOrderId:0xccb4c799749cf8b5a1cce4b3e813d335e55ea93d, transactionStatus:SUCCESS] 
==> about to get workOrderStatus
==> workOrderIsRevealing: false
[19/Dec/2018:08:57:54 +0000] [xtremweb.worker.ThreadLaunch_ThreadAlive_18] ERROR : getThreadByWorkUid() can't find work 02609702-92fc-4105-a54b-9bccdfad53fb
[19/Dec/2018:08:57:54 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] WARN : workAlive(02609702-92fc-4105-a54b-9bccdfad53fb) can't find working thread
```

**Comment by branciard** [comment]
This workorder has an issue at revealing phase. We will analyse this deeper after the workerdrop: https://explorer.iex.ec/mainnet/work/0xCCB4c799749cF8B5a1CCe4B3E813d335e55Ea93d . We will manually reward RLC you also after the workerdrop end. You can stop/start your worker again for others works.

**Comment by branciard** [comment]
Can you provide your public worker address. Thanks.

**Comment by Vince427** [comment]
Hi, I have the same problem, my worker name is vf42 (1f57cf03-5390-4c35-8539-7af8d4ce26e3)

Communcation : WORKREQUEST 
09:13:10.856 [ThreadAlive] INFO  c.i.w.workerpool.WorkerPoolService - GetContributionModel [workOrderId:0x738574704e8879a570e1a05c049254b9d7ae5aeb, transactionStatus:SUCCESS] 
==> about to get workOrderStatus
==> workOrderIsRevealing: false
[19/Dec/2018:09:13:13 +0000] [xtremweb.worker.ThreadLaunch_ThreadAlive_18] ERROR : getThreadByWorkUid() can't find work bb9e8a89-8c87-4cc1-8560-e92eb5d91843
[19/Dec/2018:09:13:13 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] WARN : workAlive(bb9e8a89-8c87-4cc1-8560-e92eb5d91843) can't find working thread
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at xtremweb.worker.PoolWork.removeWork(PoolWork.java:310)
	at xtremweb.worker.ThreadAlive.checkJob(ThreadAlive.java:341)
	at xtremweb.worker.ThreadAlive.run(ThreadAlive.java:155)
[19/Dec/2018:09:13:14 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Ping = 777 ms
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at xtremweb.worker.PoolWork.removeWork(PoolWork.java:310)
	at xtremweb.worker.ThreadAlive.synchronize(ThreadAlive.java:439)
	at xtremweb.worker.ThreadAlive.run(ThreadAlive.java:136)
[19/Dec/2018:09:13:15 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Alive period from server = 60
[19/Dec/2018:09:13:25 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
[19/Dec/2018:09:13:40 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST

**Comment by fab-io** [comment]
I have restart the worker.

Before the restart my worker uid was: 8fa6ea9c-4520-45ed-8ea6-90750c790297 (gastone)
is this the address you are looking for?

**Comment by branciard** [comment]
thank you. With the id given. I found your public worker address : 0x1993c70a2ca963455a253f15cdb42453fa52b840. I will reward on it after the analyse and the workerdrop end.

**Comment by branciard** [comment]
@Vince427 I open an issue for your worker public address : 0xdec41ab8a95cd64e9952addea8ee8afb11c294b9 right ?  and analyse and treat it after the workerdrop : https://github.com/iExecBlockchainComputing/workerdrop-scripts-public/issues/43

**Comment by Vince427** [comment]
yes it's the right address

**Comment by Vince427** [comment]
Another work after restart and the same error

12:23:00.979 [ThreadAlive] INFO  c.i.w.workerpool.WorkerPoolService - GetContributionModel [workOrderId:0xc8000555b495fb8fa3d28edc54563fdd59e30042, transactionStatus:SUCCESS] 
==> about to get workOrderStatus
==> workOrderIsRevealing: false
[19/Dec/2018:12:23:03 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
[19/Dec/2018:12:23:04 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Ping = 836 ms
[19/Dec/2018:12:23:05 +0000] [xtremweb.worker.ThreadAlive_ThreadAlive_18] INFO : Alive period from server = 60
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at xtremweb.common.WorkInterface.setRevealing(WorkInterface.java:2233)
	at xtremweb.worker.ThreadAlive.synchronize(ThreadAlive.java:477)
	at xtremweb.worker.ThreadAlive.run(ThreadAlive.java:136)
[19/Dec/2018:12:23:18 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
[19/Dec/2018:12:23:33 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
[19/Dec/2018:12:23:48 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST 
[19/Dec/2018:12:24:03 +0000] [xtremweb.worker.CommLL_CommManager_14] INFO : Added Communcation : WORKREQUEST

**Comment by branciard** [comment]
@fab-io 23 RLC Manual Reward  done for worker 0x1993c70a2ca963455a253f15cdb42453fa52b840 see tx : https://etherscan.io/tx/0x4271e2e736755978e305155d43d88dc7354a9b147a8502881d82b381b81bd80d
